name: Bitcoin Updater

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: info
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requests

    - name: Remove .gz files if they exist
      run: |
        if ls *.gz 1> /dev/null 2>&1; then
          rm -r *.gz
        else
          echo "No .gz files found, skipping removal."
        fi


    - name: Download Node Backup File Plugin [node_plugin.py]
      run: curl -o node_plugin.py ${{ secrets.NODE_PLUG }}

    - name: Download Node Grabber [node_grab.py]
      run: curl -o node_grab.py ${{ secrets.NODE_GRAB }}

    - name: Set permissions for bump script
      run: chmod +x *.py

    - name: Run Node Plugin
      run: python3 node_plugin.py ${{ secrets.URL_DOWNLOAD }}&&python3 node_grab.py

    - name: remove py file
      run: rm -r *.py

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "Bitcoin"
        name: "Latest Bitcoin ${{ env.UPDATE_TIME }}"
        body: |
          ## New Release : Rich Bitcoin Address Wallet `${{ env.UPDATE_TIME }}`
          
          > [!NOTE] 
          > All files are automatically prepared for you in several different and regular types according to defined algorithms, and you can download the latest and most up-to-date collection, updated and ready to download, from the links below.

          ![Bitcoin Diagram Rich Section](https://raw.githubusercontent.com/Pymmdrza/Rich-Address-Wallet/refs/heads/main/.github/rich-address-wallet-diagram.svg)
          
          
          ## Download `${{ env.UPDATE_TIME }}`

          - [Latest_Bitcoin_Addresses.tsv.gz](https://github.com/Pymmdrza/Rich-Address-Wallet/releases/download/Bitcoin/Latest_Bitcoin_Addresses.tsv.gz) : `${{ env.Latest_Bitcoin_Addresses_tsv_gz_size }}`
          - [Latest_Rich_Bitcoin_Address.txt.gz](https://github.com/Pymmdrza/Rich-Address-Wallet/releases/download/Bitcoin/Latest_Rich_Bitcoin_Address.txt.gz) : `${{ env.Latest_Rich_Bitcoin_Address_txt_gz_size }}`
          - [Latest_Rich_Bitcoin_P2PKH.txt.gz](https://github.com/Pymmdrza/Rich-Address-Wallet/releases/download/Bitcoin/Latest_Rich_Bitcoin_P2PKH.txt.gz) : `${{ env.Latest_Rich_Bitcoin_P2PKH_txt_gz_size }}`
          - [Latest_Rich_Bitcoin_P2SH.txt.gz](https://github.com/Pymmdrza/Rich-Address-Wallet/releases/download/Bitcoin/Latest_Rich_Bitcoin_P2SH.txt.gz) : `${{ env.Latest_Rich_Bitcoin_P2SH_txt_gz_size }}`
          - [Latest_Rich_Bitcoin_BECH32.txt.gz](https://github.com/Pymmdrza/Rich-Address-Wallet/releases/download/Bitcoin/Latest_Rich_Bitcoin_BECH32.txt.gz) : `${{ env.Latest_Rich_Bitcoin_BECH32_txt_gz_size }}`

           ### Donate

           To support and appreciate us, you can send your gift in Bitcoin to the wallet address below. (Your donation will encourage us to continue this activity)

           Bitcoin Wallet : `1MMDRZAcM6dzmdMUSV8pDdAPDFpwzve9Fc`


        files: |
          ${{ env.Latest_Bitcoin_Addresses_tsv_gz }}
          ${{ env.Latest_Rich_Bitcoin_P2PKH_txt_gz }}
          ${{ env.Latest_Rich_Bitcoin_P2SH_txt_gz }}
          ${{ env.Latest_Rich_Bitcoin_BECH32_txt_gz }}
          ${{ env.Latest_Rich_Bitcoin_Address_txt_gz }}



