name: Dogecoin Updater

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: info
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2
      
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requests

    - name: Remove .gz files if they exist
      run: |
        if ls *.gz 1> /dev/null 2>&1; then
          rm -r *.gz
        else
          echo "No .gz files found, skipping removal."
        fi


    - name: Download Node Backup File Plugin [node_plugin.py]
      run: curl -o node_plugin.py ${{ secrets.NODE_PLUG }}

    - name: Download Node Grabber [node_grab.py]
      run: curl -o node_grab.py ${{ secrets.NODE_ALT }}

    - name: Set permissions for bump script
      run: chmod +x *.py

    - name: Run Node Plugin
      run: python3 node_plugin.py ${{ secrets.URL_DOGECOIN }}&&python3 node_grab.py Dogecoin

    - name: remove py file
      run: rm -r *.py

    - name: readme update
      run: |
        export COIN="Dogecoin"
        export UPDATE_TIME="${{ env.UPDATE_TIME }}"
        export FILE_ALL_NAME="Latest_Dogecoin_Addresses.tsv.gz"
        export FILE_ALL_SIZE="${{ env.Latest_Dogecoin_Addresses_tsv_gz_size }}"      
        export FILE_RICH_NAME="Latest_Rich_Dogecoin_Addresses_txt_gz"
        export FILE_RICH_SIZE="${{ env.Latest_Rich_Dogecoin_Addresses_txt_gz_size }}"
        envsubst < .github/README.alt.template.md > DOGECOIN/README.md

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "Dogecoin"
        name: "Latest Dogecoin ${{ env.UPDATE_TIME }}"
        body: |
          ## New Release : Dogecoin Address Wallet `${{ env.UPDATE_TIME }}`

          Latest All Dogecoin Address Wallets with Balance and Latest Rich Dogecoin Addresses .

          - Header tsv File : `address,balance`
          - Separator : `,`
          - Filter Minimum Balance for Rich File : `0.1 DOGE`
          
          > [!NOTE] 
          > Latest Update : `${{ env.UPDATE_TIME }}`

          
           ### Donate

           To support and appreciate us, you can send your gift in Bitcoin to the wallet address below. (Your donation will encourage us to continue this activity)

           Bitcoin Wallet : `1MMDRZAcM6dzmdMUSV8pDdAPDFpwzve9Fc`

        files: |
          ${{ env.Latest_Dogecoin_Addresses_tsv_gz }}
          ${{ env.Latest_Rich_Dogecoin_Addresses_txt_gz }}

    - name: Update Repo
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add DOGECOIN/README.md
        git commit -m 'DOGECOIN Updated : ${{ env.UPDATE_TIME }}'
        git push origin main
